# Generated by Django 3.0.2 on 2020-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
                ('kitchen', models.IntegerField(choices=[(1, 'Amerykańska'), (2, 'Azjatycka'), (3, 'Europejska'), (4, 'Indyjska'), (5, 'Pizza'), (6, 'Polska'), (7, 'Śródziemnomorska'), (8, 'Wegetariańska')], verbose_name='Kuchania')),
                ('city', models.IntegerField(choices=[(1, 'Warszawa'), (2, 'Trójmiasto'), (3, 'Wrocław')], verbose_name='Miasto')),
                ('address', models.CharField(max_length=128, verbose_name='Adres')),
                ('phone', models.IntegerField(max_length=9, verbose_name='Telefon')),
                ('www', models.URLField(verbose_name='Strona')),
            ],
        ),
    ]
