# Generated by Django 3.0.2 on 2020-01-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GdzieTeraz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.IntegerField(verbose_name='Telefon'),
        ),
    ]
