# Generated by Django 3.0.2 on 2020-01-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GdzieTeraz', '0002_auto_20200127_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa')),
                ('size', models.IntegerField(choices=[(2, 2), (4, 4), (6, 6), (8, 8)], verbose_name='Wielkość')),
                ('taken', models.BooleanField(default=False, verbose_name='Zajęty')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GdzieTeraz.Restaurant')),
            ],
        ),
    ]
