# Generated by Django 3.0.2 on 2020-01-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GdzieTeraz', '0004_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='www',
            field=models.URLField(null=True, verbose_name='Strona'),
        ),
    ]
