# Generated by Django 3.0.2 on 2020-01-29 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GdzieTeraz', '0005_auto_20200127_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='www',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='kitchen',
            field=models.IntegerField(choices=[(0, ''), (1, 'Amerykańska'), (2, 'Azjatycka'), (3, 'Europejska'), (4, 'Indyjska'), (5, 'Pizza'), (6, 'Polska'), (7, 'Śródziemnomorska'), (8, 'Wegetariańska')], verbose_name='Kuchania'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tables',
            name='size',
            field=models.IntegerField(choices=[(2, 'S'), (4, 'M'), (6, 'L'), (8, 'XL')], verbose_name='Wielkość'),
        ),
    ]
